### PR TITLE
Feature/abstract file watch

### PR DESCRIPTION
**Pull request by willread**
Port file watch logic from `rise-image` for use in `rise-video` and other components.

Component specific logic can be implemented by overriding callback functions, ie: `watchedFileAddedCallback, watchedFileErrorCallback, watchedFileDeletedCallback`.

For a reference usage, see this [rise-video pull request](https://github.com/Rise-Vision/rise-video/pull/6)

### CODE REVIEW

**Comment by stulees** [comment]
@willread The reference usage you have in rise-video branch shows listening for events instead of overriding callback functions. Can you clarify?

**Comment by willread** [comment]
@stulees My bad, I've removed those event handlers from the rise-video PR.

**Comment by stulees** [comment]
@willread Changes look good. Can you clarify how you are going to validate this works as expected in order to merge?

**Comment by willread** [comment]
@stulees I tested this branch with `rise-video/feature/watch-files` and a local test template which populates the `files` attribute of the `<rise-video>` element with a list of video files I uploaded to rise storage, verified that files were being synced from rise storage in a chrome player and that all callbacks were being called as expected when files were added / deleted. I was planning to run through the same manual end to end testing after both this and the `rise-video` changes are merged.

**Comment by stulees** [comment]
@willread Nice, sounds good. These changes are low risk since they are providing a new mixin that nothing in production is using. We should not use this mixin in _rise-image_ until we eventually have _rise-video_ complete and fully tested/validated. Cheers

**Pull request merged**
